config/routes.rb
Rails.application.routes.draw do
  # Shortcut Routes
  get 'landing/index'
  get '/signup',     to: 'users#new'
  get '/login',      to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Resources, alphabetized
  resources :database_connection
  resources :queries do
    get '/email', to: 'queries#email'
    get '/toggle-daily-digest', to: 'queries#toggle_daily_digest'
  end
  resources :users
  resources :visualizations

  # Root
  root 'landing#index'
end

app/models/visualization.rb
class Visualization < ActiveRecord::Base
  include FriendlyId

  friendly_id :name, use: :slugged
  
  belongs_to :saved_query
end

app/controllers/visualizations_controller.rb
class VisualizationsController < ApplicationController
  before_filter :authenticate!

  def new
    @visualization = Visualization.new
    @saved_queries = SavedQuery.all
  end

  def index
    @visualizations = Visualization.all
  end

  def create
    @visualization = Visualization.new
    if @visualization.update_attributes(visualization_params)
      redirect_to visualization_path(@visualization)
    else
      render :new
    end
  end

  def update
    find_visualization
    @visualization.code = params[:code]
    
    if @visualization.save
      redirect_to visualization_path(@visualization)
    else
      render :show
    end
  end

  def show
    find_visualization
    query_runner = QueryRunner.new(
      database_connection: @saved_query.database_connection
    )
    @json_data = query_runner.run(@saved_query.query, :json)
    
  end

  private

  def visualization_params
    params.require(:visualization).permit(:name, :saved_query_id)
  end
  
  def find_visualization
    @visualization = Visualization.friendly.find(params[:id])
    @saved_query = @visualization.saved_query
  end
end

app/helpers/visualizations_helper.rb
module VisualizationsHelper
end

app/views/visualizations/_controls.html.erb
<a class="btn btn-primary btn-xs" role="button" data-toggle="collapse" href="#viz-controls" aria-expanded="false" aria-controls="viz-controls">Toggle Controls</a>
<div id="viz-controls" class="collapse panel panel-default">
  <div class="panel-body">
    <div id="viz-editor"><%= @visualization.code %></div>
    <%= form_for(@visualization, url: visualization_path(@visualization), method: :patch) do |f| %>
      <textarea name="code"><%= @visualization.code %></textarea>
      <%= f.submit "Save & Run", class: "btn btn-primary" %>
    <%- end %>
  </div>
  <div class="panel-body">
    <p class="lead">What is this?</p>
    <p>Override the <code>generateHighCharts(jsonData, transformedData)</code> function above to return a valid HighCharts configuration object.</p>
  </div>
  <div class="panel-body">
    <p>Standard JSON (<code>jsonData</code>)</p>
    <pre id="json-data"><%= @json_data %></pre>
    <p>Transformed JSON (<code>transformedData</code>)</p>
    <pre id="json-data-transformed"></pre>
  </div>
  <div class="panel-footer">
    <%= link_to "HighCharts Docs", "http://api.highcharts.com/highcharts", target: "_blank" %>
  </div>
</div>

app/views/visualizations/_viz.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div id="viz"></div>
  </div>
</div>
<%= render "controls" %>
<%= javascript_include_tag "visualizations" %>

app/views/visualizations/index.html.erb
<div class="row">
  <div class="panel panel-default">
    <div class="panel-body">
      <h2>Visualizations</h2>
      <%= link_to "New Visualization", new_visualization_path, class: "btn btn-primary pull-right" %>
    </div>
    <table class="table">
      <tr>
        <th>Visualization</th>
      </tr>
      <%- @visualizations.each do |viz| %>
        <tr>
          <td><%= link_to viz.name, visualization_path(viz) %></td>
        </tr>
      <%- end %>
    </table>
  </div>
</div>

app/views/visualizations/new.html.erb
<%= render "shared/error_messages", model: @visualization %>

<div class="row">
  <div class="col-md-4">
  <h2>New Visualization</h2>
  <%= form_for(@visualization) do |f| %>
    <div class="form-group">
      <label>Name</label>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <label>Select a query to visualize</label>
      <%= f.select(:saved_query_id, options_for_select(@saved_queries.map{|sv| [sv.name, sv.id]}), {}, {class: "form-control"}) %>
    </div>
    <div class="form-group">
      <%= f.submit "Create Visualization", class: "btn btn-primary" %>
    </div>
  <%- end %>
  </div>
</div>

app/views/visualizations/show.html.erb
<div class="row">
  <h1><%= link_to @visualization.name, visualization_path(@visualization) %></h1>
</div>

<div class="row">
  <div class="pull-left">
    <small>
      Created <%= time_ago_in_words(@visualization.created_at) %> ago from
      <%= link_to @visualization.saved_query.name, query_path(@visualization.saved_query) %>.
    </small>
    <div class="clearfix"></div>
    <small>Modified <%= time_ago_in_words(@visualization.updated_at) %> ago.</small>
  </div>
  <div class="form-group form-inline pull-right">
    Share: <input class="form-control" value="<%= visualization_url(@visualization) %>" readonly />
  </div>
</div>



<div class="row">
  <%= render "shared/error_messages", model: @visualization %>
  <%= render "viz" %>
</div>