config/routes.rb
Rails.application.routes.draw do
  # Shortcut Routes
  get 'landing/index'
  get '/signup',     to: 'users#new'
  get '/login',      to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Resources, alphabetized
  resources :database_connection
  resources :queries do
    get '/email', to: 'queries#email'
    get '/toggle-daily-digest', to: 'queries#toggle_daily_digest'
  end
  resources :users
  resources :visualizations

  # Root
  root 'landing#index'
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  before_filter :authenticate!, except: [:show]
  before_filter :preflight_check, only: [:index, :new, :show]
  
  def index
    @saved_queries = SavedQuery.recent
    load_all_database_connections
  end

  def new
    @saved_query = SavedQuery.new
    load_all_database_connections
  end

  def create
    load_all_database_connections
    @saved_query = SavedQuery.new(query_params.merge({user_id: current_user.id}))
    if @saved_query.save
      redirect_to query_path(@saved_query)      
    else
      render :new
    end
  end

  def show
    find_query
    authorize_show!
    load_all_database_connections
        
    respond_to do |format|
      format.html do
        run_query(format: :html)
      end
      format.json do
        run_query(format: :json)
        render json: @result_json
      end
      format.csv do
        run_query(format: :csv)
        send_data @result_csv
      end
    end
  end

  def email
    @query_id = params[:query_id]
    @saved_query = SavedQuery.friendly.find(@query_id)
    authorize_show!
    load_all_database_connections
    if SavedQueries.simple(@saved_query, current_user.email).deliver
      flash[:notice] = "Your email has been sent."
      redirect_to query_path(@saved_query)
    end
  end

  def toggle_daily_digest
    @query_id = params[:query_id]
    @saved_query = SavedQuery.friendly.find(@query_id)
    authorize_show!

    @saved_query.toggle_daily_digest
    if !@saved_query.save
      flash[:error] = "An error occurred."
    end
    redirect_to query_path(@saved_query)
  end

  def destroy
    find_query
    load_all_database_connections
    if @saved_query.destroy
      flash[:notice] = "Deleted saved query."
      redirect_to queries_path
    else
      render :show
    end
  end

  def update
    find_query
    authorize_update!
    load_all_database_connections

    if @saved_query.update_attributes(query_params)
      redirect_to query_path(@saved_query)
    else
      render :show
    end
  end

  private

  def query_params
    params.permit(:name, :query, :database_connection_id, :privacy)
  end
  
  def load_query
    @query = params[:query]
  end

  def find_query
    @query_id = params[:id]
    @saved_query = SavedQuery.friendly.find(@query_id)
  end

  def authorize_update!
    if !policy(@saved_query).edit?
      flash[:notice] = "Please log in."
      redirect_to login_path
    end
  end

  def authorize_show!
    if !policy(@saved_query).read?
      if logged_in?
        flash[:notice] = "That QueryClip is private. Please check with the owner."
        redirect_to root_path
      else
        flash[:notice] = "Please log in."
        redirect_to login_path
      end
    end
  end
  
  def load_database_connection
    @database_connection = DatabaseConnection.find(params[:database_connection_id])
  end

  def run_query(options = {})
    format = options[:format]
    raise "No format specified" if format.nil?

    query_runner = QueryRunner.new(
      database_connection: @saved_query.database_connection
    )

    case format
    when :html
      @result = query_runner.run(@saved_query.query, :raw)
      @result_json = query_runner.run(@saved_query.query, :json)
    when :csv
      @result_csv = query_runner.run(@saved_query.query, :csv)
    when :json
      @result_json = query_runner.run(@saved_query.query, :json)
    end

    @result
  rescue QueryException => e
    @error = e
  end

  def load_all_database_connections
    @database_connections = DatabaseConnection.all
  end
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/queries/_database_connection_selector.html.erb
<div class="form-group form-inline">
  <label>Database:</label>
  <%- if policy(@saved_query).edit? %>
  
  <select id="database_connection_id" name="database_connection_id" class="form-control">
    <%- @database_connections.each do |conn| %>
      <%- if @saved_query && @saved_query.database_connection && @saved_query.database_connection.id == conn.id %>
        <option value="<%= conn.id %>" selected><%= conn.name %></option>
      <%- else %>
        <option value="<%= conn.id %>"><%= conn.name %></option>
      <%- end %>
    <%- end %>
  </select>

  <%- else %>

  <%= @saved_query.database_connection.name %>
  
  <%- end %>
</div>

app/views/queries/_debug.html.erb
<%- if ENV['DEBUG'] %>

<h1>Debug Info</h1>

<table class="table">
  <tr>
    <th>Variable</th>
    <th>Value</th>
  </tr>
  <tr>
    <td>@database_connection</td>
    <td><%= @database_connection.inspect %></td>
  </tr>
  <tr>
    <td>@query</td>
    <td><%= @query.inspect %></td>
  </tr>
  <tr>
    <td>@results</td>
    <td><%= @results.inspect %></td>
  </tr>
  <tr>
    <td>@error</td>
    <td><%= @error.inspect %></td>
  </tr>
</table>

<%- end %>

app/views/queries/_error_message.html.erb
<pre class="bg-danger">
  <%= @error.message %>
</pre>

app/views/queries/_exports.html.erb
<div class="btn-group">
  <button type="button" class="btn btn-info btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Export <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li>
      <%= link_to "CSV", query_path(@saved_query, format: :csv) %>
    </li>
    <li>
      <%= link_to "JSON", query_path(@saved_query, format: :json) %>
    </li>
    <li>
      <%= link_to "Email", query_email_path(@saved_query) %>
    </li>
  </ul>
</div>

app/views/queries/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%- if @saved_query.id.nil? %>
      <%= form_for(@saved_query, url: queries_path, method: :post) do |f| %>
        <%= render "form_body" %>
      <%- end %>
    <%- else %>
      <%= form_for(@saved_query, url: query_path(@saved_query), method: :patch) do |f| %>
        <%= render "form_body" %>
      <%- end %>
    <%- end %>
  </div>
</div>

app/views/queries/_form_body.html.erb
<%= render "shared/error_messages", model: @saved_query %>

<div class="form-group">
  <%- if policy(@saved_query).edit? %>
    <input type="text" name="name" placeholder="Name your query..." class="form-control" value="<%= @saved_query.name %>" />
  <%- else %>
    <input type="text" name="name" placeholder="Name your query..." class="form-control" value="<%= @saved_query.name %>" disabled />
  <%- end %>
</div>
<%= render "query_box" %>
<%= render "database_connection_selector" %>
<%= render "privacy_selector" if policy(@saved_query).edit? %>
<div class="form-group">
  <%- if policy(@saved_query).edit? %>
    <input type="submit" value="Run Query Clip" class="btn btn-primary form-control" />
  <%- else %>
    <input type="submit" value="Run Query Clip" class="btn btn-primary form-control" disabled />
  <%- end %>

</div>

app/views/queries/_privacy_selector.html.erb
<div class="form-group form-inline">
  <label>Privacy:</label>
  <select id="privacy" name="privacy" class="form-control">
    <%- SavedQuery.privacy_options.each do |scope| %>
      <%- if @saved_query.privacy == scope %>
        <option value="<%= scope %>" selected><%= scope %></option>
      <%- else %>
        <option value="<%= scope %>"><%= scope %></option>
      <%- end %>
    <%- end %>
  </select>
</div>

app/views/queries/_query_box.html.erb
<div class="form-group">
  <textarea name="query" placeholder="Here goes your query" class="form-control" editable="<%= policy(@saved_query).edit? %>"><%= @saved_query.query %></textarea>
  <div id="query-box"><%= @saved_query.query %></div>
</div>
<script>
  var queryEditor = ace.edit("query-box");
  queryEditor.getSession().setMode("ace/mode/sql");
  var textarea = $('textarea[name="query"]').hide();
  var editable = $('textarea[name="query"]').attr("editable");
  var readonly = false;
  if (editable == "false")
    readonly = true;
  queryEditor.setOptions({
    minLines: 10,
    maxLines: Infinity,
    showPrintMargin: false
  });
  queryEditor.setReadOnly(readonly);
  queryEditor.getSession().setValue(textarea.val());
  queryEditor.getSession().on('change', function(){
    textarea.val(queryEditor.getSession().getValue());
  });
</script>

app/views/queries/_results_table.html.erb
<%- if @result[:rows].count < 1 %>
  <h1>No results.</h1>
<%- else %>
<h3>Results</h3>
<table class="table">
  <tr>
    <%- @result[:fields].each do |field| %>
      <th><%= field %></th>
    <%- end %>
  </tr>
  <%- @result[:rows].each do |row| %>
  <tr>
    <%- row.each do |col| %>
      <td><%= col %></td>
    <%- end %>
  </tr>
  <%- end %>
</table>
<%- end %>

app/views/queries/_saved_queries.html.erb
<table class="table">
  <tr>
    <th>Name</th>
    <th>User</th>
    <th>Created On</th>
  </tr>
  
  <%- @saved_queries.each do |sq| %>
    <tr>
      <td>
        <h4><%= link_to sq.name, query_path(sq) %></h4>
        <span class="label label-info"><%= sq.privacy.capitalize %></span>
        <div class="clearfix" />
        <small><%= sq.database_connection.name %></small>
      </td>
      <td>
        <%= link_to sq.user.email, user_path(sq.user) %>
      </td>
      <td><%= time_ago_in_words(sq.created_at) %> ago</td>
    </tr>
  <%- end %>
</table>

app/views/queries/_settings.html.erb
<div class="btn-group">
  <button type="button" class="btn btn-warning btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Settings <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li>
      <%= link_to "Schema Explorer", database_connection_path(@saved_query.database_connection, anchor: 'tables'), target: '_blank' %>
    </li>
    <li>
      <%- if @saved_query.daily_digest %>
        <%= link_to "Exclude from daily digest", query_toggle_daily_digest_path(@saved_query) %>
      <%- else %>
        <%= link_to "Include in daily digest", query_toggle_daily_digest_path(@saved_query) %>
      <%- end %>
    </li>
    <li class="bg-danger">
      <%= link_to "Delete query", query_path(@saved_query), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  </ul>
</div>

app/views/queries/index.html.erb
<h2>All Query Clips</h2>
<div class="panel panel-default">
  <div class="panel-body">
    <%= link_to "Create query clip", new_query_path, class: 'btn btn-primary pull-right' %>
  </div>
  <%= render "saved_queries" %>
</div>

app/views/queries/new.html.erb
<h1>New Query</h1>
<%- if DatabaseConnection.count < 1 %>
    <div class="jumbotron">
      <p>Please add a database before creating a new query.</p>
      <p><%= link_to "Create a database", new_database_connection_path, class: "btn btn-primary" %></p>
    </div>
<%- else %>
  <%= render "form" %>
<%- end %>

app/views/queries/show.html.erb
<div class="row">
  <h1><%= link_to @saved_query.name, query_path(@saved_query) %></h1>
</div>
<div class="row">
  <div class="pull-left">
    <small>Created <%= time_ago_in_words(@saved_query.created_at) %> ago by <%= link_to @saved_query.user.email, user_path(@saved_query.user) %>.</small>
    <div class="clearfix"></div>
    <small>Modified <%= time_ago_in_words(@saved_query.updated_at) %> ago.</small>
  </div>
  <div class="form-group form-inline pull-right">
    <%= render "settings" if policy(@saved_query).edit? %>
    <%= render "exports" %>
    Share: <input class="form-control" value="<%= query_url(@saved_query) %>" readonly />
  </div>
</div>
<div class="row">
  <%= render "error_message" if @error %>
  <%= render "form" %>
  <%= render "results_table", result: @result if @result %>
  <%= render "debug" %>
</div>