config/routes.rb
Rails.application.routes.draw do
  # Shortcut Routes
  get 'landing/index'
  get '/signup',     to: 'users#new'
  get '/login',      to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Resources, alphabetized
  resources :database_connection
  resources :queries do
    get '/email', to: 'queries#email'
    get '/toggle-daily-digest', to: 'queries#toggle_daily_digest'
  end
  resources :users
  resources :visualizations

  # Root
  root 'landing#index'
end

app/views/layouts/_flash.html.erb
<div class="flash">
  <%- if flash[:notice] %>
    <p class="alert alert-info" role="alert">
      <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
      <%= flash[:notice] %>
    </p>
  <%- end %>
  <%- if flash[:error] %>
    <p class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-alert" aria-hidden="true"></span>
      <%= flash[:error] %>
    </p>
  <%- end %>
</div>

app/views/layouts/_footer.html.erb
<div class="row">
  <hr />
  <ul class="list-inline">
    <li>
      <%= link_to "QueryClips", "http://www.queryclips.com", target: "_blank" %>
    </li>
    <li>
      <%= link_to "Twitter", "https://twitter.com/queryclips", target: "_blank" %>
    </li>
</div>
<div class="clearfix"></div>

app/views/layouts/_navigation.html.erb
<div class="row">
  <ul class="nav nav-pills">
    <li role="presentation"><%= link_to "Home", root_path %></li>
    <%- if logged_in? %>
      <li role="presentation"><%= link_to "Query clips", queries_path %></li>
      <li role="presentation"><%= link_to "Visualizations", visualizations_path %></li>
      <li role="presentation"><%= link_to "Databases", database_connection_index_path %></li>
      <li role="presentation"><%= link_to "Users", users_path %></li>
      <li role="presentation"><%= link_to "Log out #{current_user.email}", logout_path, method: :delete %></li>
    <%- else %>
      <%- unless signup_disallowed? %>
        <li role="presentation"><%= link_to "Sign Up", signup_path %></li>
      <%- end %>
      <li role="presentation"><%= link_to "Log In", login_path %></li>
    <%- end %>
  </ul>
</div>

app/views/layouts/_preflight_check.html.erb
<div class="preflight-check">

  <%- if DatabaseConnection.count < 1 %>
    <p class="alert alert-warning" role="alert">
      <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
      You haven't configured any databases yet.
      <%= link_to "Click here", new_database_connection_path %>
      to add your first database connection.
    </p>
  <%- else %>
    <%- if SavedQuery.count < 1 %>
      <p class="alert alert-warning" role="alert">  
        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
        You haven't added any query clips yet.
        <%= link_to "Click here", new_query_path %>
        to add your first query clip.
      </p>
    <%- end %>    
  <%- end %>

  <%- if ENV['HOST'].nil? %>
    <p class="alert alert-warning" role="alert">
      <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
      You haven't configured a HOST environment variable. This will prevent certain features from functioning. Please see the
      <%= link_to "README", "https://github.com/dpaola2/QueryClips", target: "_blank" %>
      for more information.
    </p>
  <%- end %>
  
  <%- if @preflight_check_smtp %>
    <p class="alert alert-warning" role="alert">
      <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
      You haven't configured SMTP settings. This will prevent mail from being sent. Please see the
      <%= link_to "README", "https://github.com/dpaola2/QueryClips", target: "_blank" %>
      for more information.
    <p>
  <%- end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>QueryClips</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/mode-sql.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/mode-json.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/4.2.3/highcharts.js"></script>
  <div class="container">
    <%= render "layouts/navigation" %>
    <%= render "layouts/flash" %>
    <%= render "layouts/preflight_check" if @preflight_check %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </div>

</body>
</html>